### PR TITLE
Parse timestamp requests from JSON

### PR DESCRIPTION
**Pull request by malancas**
This adds struct annotations and a new function that allows us to parse a timestamp request from JSON. It also fixes a few typos found throughout the code.

### CODE REVIEW

**Comment by vanbroup** [comment]
Can you provide some background information on why you would want to add keeping support, this doesn't seem to be the most efficient or a standard way for handling timestamps.

**Comment by malancas** [comment]
> Can you provide some background information on why you would want to add keeping support, this doesn't seem to be the most efficient or a standard way for handling timestamps.

Sure, I'm working on the Sigstore Timestamp Authority project and we are adding support for making timestamp requests in JSON format (see https://github.com/sigstore/timestamp-authority/issues/229). We have some clients working in Javascript who would like make requests to the timestamp authority but there is minimal tooling for working with ASN.1 in Javascript and some other languages.

**Comment by vanbroup** [comment]
I see the problem; this would deviate from RFC3161 and add a dependency on `encoding/json` which could raise the question why not GRPC or other formats?

What if you would parse client request in the API request handler and call `CreateRequest` instead pf `ParseRequest`?

**Comment by malancas** [comment]
> I see the problem; this would deviate from RFC3161 and add a dependency on `encoding/json` which could raise the question why not GRPC or other formats?
> 
> What if you would parse client request in the API request handler and call `CreateRequest` instead of `ParseRequest`?

I think using `CreateRequest` instead will work, I'll try using that. Thanks for the suggestion

**Pull request closed without merging**
